# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from stonefish_ros/INS.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg
import stonefish_ros.msg

class INS(genpy.Message):
  _md5sum = "aea13212cea3e4dea3f14d7fcc89e387"
  _type = "stonefish_ros/INS"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

# Global position of robot
float64 latitude
float64 longitude

# Global position of NED origin
float64 origin_latitude
float64 origin_longitude

# Robot pose in NED
NEDPose pose
NEDPose pose_variance
float64 altitude

# Robot body velocity
geometry_msgs/Vector3 body_velocity
geometry_msgs/Vector3 rpy_rate
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: stonefish_ros/NEDPose
float64 north
float64 east
float64 down
float64 roll
float64 pitch
float64 yaw
================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','latitude','longitude','origin_latitude','origin_longitude','pose','pose_variance','altitude','body_velocity','rpy_rate']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','stonefish_ros/NEDPose','stonefish_ros/NEDPose','float64','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,latitude,longitude,origin_latitude,origin_longitude,pose,pose_variance,altitude,body_velocity,rpy_rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(INS, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.origin_latitude is None:
        self.origin_latitude = 0.
      if self.origin_longitude is None:
        self.origin_longitude = 0.
      if self.pose is None:
        self.pose = stonefish_ros.msg.NEDPose()
      if self.pose_variance is None:
        self.pose_variance = stonefish_ros.msg.NEDPose()
      if self.altitude is None:
        self.altitude = 0.
      if self.body_velocity is None:
        self.body_velocity = geometry_msgs.msg.Vector3()
      if self.rpy_rate is None:
        self.rpy_rate = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.latitude = 0.
      self.longitude = 0.
      self.origin_latitude = 0.
      self.origin_longitude = 0.
      self.pose = stonefish_ros.msg.NEDPose()
      self.pose_variance = stonefish_ros.msg.NEDPose()
      self.altitude = 0.
      self.body_velocity = geometry_msgs.msg.Vector3()
      self.rpy_rate = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_23d().pack(_x.latitude, _x.longitude, _x.origin_latitude, _x.origin_longitude, _x.pose.north, _x.pose.east, _x.pose.down, _x.pose.roll, _x.pose.pitch, _x.pose.yaw, _x.pose_variance.north, _x.pose_variance.east, _x.pose_variance.down, _x.pose_variance.roll, _x.pose_variance.pitch, _x.pose_variance.yaw, _x.altitude, _x.body_velocity.x, _x.body_velocity.y, _x.body_velocity.z, _x.rpy_rate.x, _x.rpy_rate.y, _x.rpy_rate.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = stonefish_ros.msg.NEDPose()
      if self.pose_variance is None:
        self.pose_variance = stonefish_ros.msg.NEDPose()
      if self.body_velocity is None:
        self.body_velocity = geometry_msgs.msg.Vector3()
      if self.rpy_rate is None:
        self.rpy_rate = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 184
      (_x.latitude, _x.longitude, _x.origin_latitude, _x.origin_longitude, _x.pose.north, _x.pose.east, _x.pose.down, _x.pose.roll, _x.pose.pitch, _x.pose.yaw, _x.pose_variance.north, _x.pose_variance.east, _x.pose_variance.down, _x.pose_variance.roll, _x.pose_variance.pitch, _x.pose_variance.yaw, _x.altitude, _x.body_velocity.x, _x.body_velocity.y, _x.body_velocity.z, _x.rpy_rate.x, _x.rpy_rate.y, _x.rpy_rate.z,) = _get_struct_23d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_23d().pack(_x.latitude, _x.longitude, _x.origin_latitude, _x.origin_longitude, _x.pose.north, _x.pose.east, _x.pose.down, _x.pose.roll, _x.pose.pitch, _x.pose.yaw, _x.pose_variance.north, _x.pose_variance.east, _x.pose_variance.down, _x.pose_variance.roll, _x.pose_variance.pitch, _x.pose_variance.yaw, _x.altitude, _x.body_velocity.x, _x.body_velocity.y, _x.body_velocity.z, _x.rpy_rate.x, _x.rpy_rate.y, _x.rpy_rate.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = stonefish_ros.msg.NEDPose()
      if self.pose_variance is None:
        self.pose_variance = stonefish_ros.msg.NEDPose()
      if self.body_velocity is None:
        self.body_velocity = geometry_msgs.msg.Vector3()
      if self.rpy_rate is None:
        self.rpy_rate = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 184
      (_x.latitude, _x.longitude, _x.origin_latitude, _x.origin_longitude, _x.pose.north, _x.pose.east, _x.pose.down, _x.pose.roll, _x.pose.pitch, _x.pose.yaw, _x.pose_variance.north, _x.pose_variance.east, _x.pose_variance.down, _x.pose_variance.roll, _x.pose_variance.pitch, _x.pose_variance.yaw, _x.altitude, _x.body_velocity.x, _x.body_velocity.y, _x.body_velocity.z, _x.rpy_rate.x, _x.rpy_rate.y, _x.rpy_rate.z,) = _get_struct_23d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_23d = None
def _get_struct_23d():
    global _struct_23d
    if _struct_23d is None:
        _struct_23d = struct.Struct("<23d")
    return _struct_23d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
