// Generated by gencpp from file stonefish_ros/EventArray.msg
// DO NOT EDIT!


#ifndef STONEFISH_ROS_MESSAGE_EVENTARRAY_H
#define STONEFISH_ROS_MESSAGE_EVENTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <stonefish_ros/Event.h>

namespace stonefish_ros
{
template <class ContainerAllocator>
struct EventArray_
{
  typedef EventArray_<ContainerAllocator> Type;

  EventArray_()
    : header()
    , height(0)
    , width(0)
    , events()  {
    }
  EventArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , height(0)
    , width(0)
    , events(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _height_type;
  _height_type height;

   typedef uint32_t _width_type;
  _width_type width;

   typedef std::vector< ::stonefish_ros::Event_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::stonefish_ros::Event_<ContainerAllocator> >> _events_type;
  _events_type events;





  typedef boost::shared_ptr< ::stonefish_ros::EventArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stonefish_ros::EventArray_<ContainerAllocator> const> ConstPtr;

}; // struct EventArray_

typedef ::stonefish_ros::EventArray_<std::allocator<void> > EventArray;

typedef boost::shared_ptr< ::stonefish_ros::EventArray > EventArrayPtr;
typedef boost::shared_ptr< ::stonefish_ros::EventArray const> EventArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stonefish_ros::EventArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stonefish_ros::EventArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stonefish_ros::EventArray_<ContainerAllocator1> & lhs, const ::stonefish_ros::EventArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.events == rhs.events;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stonefish_ros::EventArray_<ContainerAllocator1> & lhs, const ::stonefish_ros::EventArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stonefish_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stonefish_ros::EventArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stonefish_ros::EventArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_ros::EventArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_ros::EventArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_ros::EventArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_ros::EventArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stonefish_ros::EventArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e8beee5a6c107e504c2e78903c224b8";
  }

  static const char* value(const ::stonefish_ros::EventArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e8beee5a6c107e5ULL;
  static const uint64_t static_value2 = 0x04c2e78903c224b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::stonefish_ros::EventArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stonefish_ros/EventArray";
  }

  static const char* value(const ::stonefish_ros::EventArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stonefish_ros::EventArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 height\n"
"uint32 width\n"
"Event[] events\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: stonefish_ros/Event\n"
"uint16 x\n"
"uint16 y\n"
"time ts\n"
"bool polarity\n"
;
  }

  static const char* value(const ::stonefish_ros::EventArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stonefish_ros::EventArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.events);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EventArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stonefish_ros::EventArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stonefish_ros::EventArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "events: ";
    if (v.events.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.events.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::stonefish_ros::Event_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.events[i]);
    }
    if (v.events.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // STONEFISH_ROS_MESSAGE_EVENTARRAY_H
