// Generated by gencpp from file stonefish_ros/INS.msg
// DO NOT EDIT!


#ifndef STONEFISH_ROS_MESSAGE_INS_H
#define STONEFISH_ROS_MESSAGE_INS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <stonefish_ros/NEDPose.h>
#include <stonefish_ros/NEDPose.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace stonefish_ros
{
template <class ContainerAllocator>
struct INS_
{
  typedef INS_<ContainerAllocator> Type;

  INS_()
    : header()
    , latitude(0.0)
    , longitude(0.0)
    , origin_latitude(0.0)
    , origin_longitude(0.0)
    , pose()
    , pose_variance()
    , altitude(0.0)
    , body_velocity()
    , rpy_rate()  {
    }
  INS_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , origin_latitude(0.0)
    , origin_longitude(0.0)
    , pose(_alloc)
    , pose_variance(_alloc)
    , altitude(0.0)
    , body_velocity(_alloc)
    , rpy_rate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _origin_latitude_type;
  _origin_latitude_type origin_latitude;

   typedef double _origin_longitude_type;
  _origin_longitude_type origin_longitude;

   typedef  ::stonefish_ros::NEDPose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::stonefish_ros::NEDPose_<ContainerAllocator>  _pose_variance_type;
  _pose_variance_type pose_variance;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _body_velocity_type;
  _body_velocity_type body_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpy_rate_type;
  _rpy_rate_type rpy_rate;





  typedef boost::shared_ptr< ::stonefish_ros::INS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stonefish_ros::INS_<ContainerAllocator> const> ConstPtr;

}; // struct INS_

typedef ::stonefish_ros::INS_<std::allocator<void> > INS;

typedef boost::shared_ptr< ::stonefish_ros::INS > INSPtr;
typedef boost::shared_ptr< ::stonefish_ros::INS const> INSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stonefish_ros::INS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stonefish_ros::INS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stonefish_ros::INS_<ContainerAllocator1> & lhs, const ::stonefish_ros::INS_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.origin_latitude == rhs.origin_latitude &&
    lhs.origin_longitude == rhs.origin_longitude &&
    lhs.pose == rhs.pose &&
    lhs.pose_variance == rhs.pose_variance &&
    lhs.altitude == rhs.altitude &&
    lhs.body_velocity == rhs.body_velocity &&
    lhs.rpy_rate == rhs.rpy_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stonefish_ros::INS_<ContainerAllocator1> & lhs, const ::stonefish_ros::INS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stonefish_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stonefish_ros::INS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stonefish_ros::INS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_ros::INS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_ros::INS_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_ros::INS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_ros::INS_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stonefish_ros::INS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aea13212cea3e4dea3f14d7fcc89e387";
  }

  static const char* value(const ::stonefish_ros::INS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaea13212cea3e4deULL;
  static const uint64_t static_value2 = 0xa3f14d7fcc89e387ULL;
};

template<class ContainerAllocator>
struct DataType< ::stonefish_ros::INS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stonefish_ros/INS";
  }

  static const char* value(const ::stonefish_ros::INS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stonefish_ros::INS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Global position of robot\n"
"float64 latitude\n"
"float64 longitude\n"
"\n"
"# Global position of NED origin\n"
"float64 origin_latitude\n"
"float64 origin_longitude\n"
"\n"
"# Robot pose in NED\n"
"NEDPose pose\n"
"NEDPose pose_variance\n"
"float64 altitude\n"
"\n"
"# Robot body velocity\n"
"geometry_msgs/Vector3 body_velocity\n"
"geometry_msgs/Vector3 rpy_rate\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: stonefish_ros/NEDPose\n"
"float64 north\n"
"float64 east\n"
"float64 down\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::stonefish_ros::INS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stonefish_ros::INS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.origin_latitude);
      stream.next(m.origin_longitude);
      stream.next(m.pose);
      stream.next(m.pose_variance);
      stream.next(m.altitude);
      stream.next(m.body_velocity);
      stream.next(m.rpy_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct INS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stonefish_ros::INS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stonefish_ros::INS_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin_latitude: ";
    Printer<double>::stream(s, indent + "  ", v.origin_latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin_longitude: ";
    Printer<double>::stream(s, indent + "  ", v.origin_longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::stonefish_ros::NEDPose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_variance: ";
    Printer< ::stonefish_ros::NEDPose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_variance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "body_velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.body_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpy_rate: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STONEFISH_ROS_MESSAGE_INS_H
