// Generated by gencpp from file stonefish_ros/NEDPose.msg
// DO NOT EDIT!


#ifndef STONEFISH_ROS_MESSAGE_NEDPOSE_H
#define STONEFISH_ROS_MESSAGE_NEDPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stonefish_ros
{
template <class ContainerAllocator>
struct NEDPose_
{
  typedef NEDPose_<ContainerAllocator> Type;

  NEDPose_()
    : north(0.0)
    , east(0.0)
    , down(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  NEDPose_(const ContainerAllocator& _alloc)
    : north(0.0)
    , east(0.0)
    , down(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _north_type;
  _north_type north;

   typedef double _east_type;
  _east_type east;

   typedef double _down_type;
  _down_type down;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::stonefish_ros::NEDPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stonefish_ros::NEDPose_<ContainerAllocator> const> ConstPtr;

}; // struct NEDPose_

typedef ::stonefish_ros::NEDPose_<std::allocator<void> > NEDPose;

typedef boost::shared_ptr< ::stonefish_ros::NEDPose > NEDPosePtr;
typedef boost::shared_ptr< ::stonefish_ros::NEDPose const> NEDPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stonefish_ros::NEDPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stonefish_ros::NEDPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stonefish_ros::NEDPose_<ContainerAllocator1> & lhs, const ::stonefish_ros::NEDPose_<ContainerAllocator2> & rhs)
{
  return lhs.north == rhs.north &&
    lhs.east == rhs.east &&
    lhs.down == rhs.down &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stonefish_ros::NEDPose_<ContainerAllocator1> & lhs, const ::stonefish_ros::NEDPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stonefish_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stonefish_ros::NEDPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stonefish_ros::NEDPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_ros::NEDPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_ros::NEDPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_ros::NEDPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_ros::NEDPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stonefish_ros::NEDPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf68106789b8189234a99c7c2b1e461e";
  }

  static const char* value(const ::stonefish_ros::NEDPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf68106789b81892ULL;
  static const uint64_t static_value2 = 0x34a99c7c2b1e461eULL;
};

template<class ContainerAllocator>
struct DataType< ::stonefish_ros::NEDPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stonefish_ros/NEDPose";
  }

  static const char* value(const ::stonefish_ros::NEDPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stonefish_ros::NEDPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 north\n"
"float64 east\n"
"float64 down\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::stonefish_ros::NEDPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stonefish_ros::NEDPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.north);
      stream.next(m.east);
      stream.next(m.down);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NEDPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stonefish_ros::NEDPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stonefish_ros::NEDPose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "north: ";
    Printer<double>::stream(s, indent + "  ", v.north);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "east: ";
    Printer<double>::stream(s, indent + "  ", v.east);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "down: ";
    Printer<double>::stream(s, indent + "  ", v.down);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STONEFISH_ROS_MESSAGE_NEDPOSE_H
