// Generated by gencpp from file stonefish_ros/RespawnRequest.msg
// DO NOT EDIT!


#ifndef STONEFISH_ROS_MESSAGE_RESPAWNREQUEST_H
#define STONEFISH_ROS_MESSAGE_RESPAWNREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace stonefish_ros
{
template <class ContainerAllocator>
struct RespawnRequest_
{
  typedef RespawnRequest_<ContainerAllocator> Type;

  RespawnRequest_()
    : name()
    , origin()  {
    }
  RespawnRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , origin(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _origin_type;
  _origin_type origin;





  typedef boost::shared_ptr< ::stonefish_ros::RespawnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stonefish_ros::RespawnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RespawnRequest_

typedef ::stonefish_ros::RespawnRequest_<std::allocator<void> > RespawnRequest;

typedef boost::shared_ptr< ::stonefish_ros::RespawnRequest > RespawnRequestPtr;
typedef boost::shared_ptr< ::stonefish_ros::RespawnRequest const> RespawnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stonefish_ros::RespawnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stonefish_ros::RespawnRequest_<ContainerAllocator1> & lhs, const ::stonefish_ros::RespawnRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.origin == rhs.origin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stonefish_ros::RespawnRequest_<ContainerAllocator1> & lhs, const ::stonefish_ros::RespawnRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stonefish_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stonefish_ros::RespawnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stonefish_ros::RespawnRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stonefish_ros::RespawnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b52185c92fe12e9d9fa1f7b585abb97";
  }

  static const char* value(const ::stonefish_ros::RespawnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b52185c92fe12e9ULL;
  static const uint64_t static_value2 = 0xd9fa1f7b585abb97ULL;
};

template<class ContainerAllocator>
struct DataType< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stonefish_ros/RespawnRequest";
  }

  static const char* value(const ::stonefish_ros::RespawnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"geometry_msgs/Pose origin\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::stonefish_ros::RespawnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.origin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RespawnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stonefish_ros::RespawnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stonefish_ros::RespawnRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STONEFISH_ROS_MESSAGE_RESPAWNREQUEST_H
