// Generated by gencpp from file stonefish_ros/Respawn.msg
// DO NOT EDIT!


#ifndef STONEFISH_ROS_MESSAGE_RESPAWN_H
#define STONEFISH_ROS_MESSAGE_RESPAWN_H

#include <ros/service_traits.h>


#include <stonefish_ros/RespawnRequest.h>
#include <stonefish_ros/RespawnResponse.h>


namespace stonefish_ros
{

struct Respawn
{

typedef RespawnRequest Request;
typedef RespawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Respawn
} // namespace stonefish_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stonefish_ros::Respawn > {
  static const char* value()
  {
    return "4dd68abb2191666666d42e4d2cd55f30";
  }

  static const char* value(const ::stonefish_ros::Respawn&) { return value(); }
};

template<>
struct DataType< ::stonefish_ros::Respawn > {
  static const char* value()
  {
    return "stonefish_ros/Respawn";
  }

  static const char* value(const ::stonefish_ros::Respawn&) { return value(); }
};


// service_traits::MD5Sum< ::stonefish_ros::RespawnRequest> should match
// service_traits::MD5Sum< ::stonefish_ros::Respawn >
template<>
struct MD5Sum< ::stonefish_ros::RespawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stonefish_ros::Respawn >::value();
  }
  static const char* value(const ::stonefish_ros::RespawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stonefish_ros::RespawnRequest> should match
// service_traits::DataType< ::stonefish_ros::Respawn >
template<>
struct DataType< ::stonefish_ros::RespawnRequest>
{
  static const char* value()
  {
    return DataType< ::stonefish_ros::Respawn >::value();
  }
  static const char* value(const ::stonefish_ros::RespawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stonefish_ros::RespawnResponse> should match
// service_traits::MD5Sum< ::stonefish_ros::Respawn >
template<>
struct MD5Sum< ::stonefish_ros::RespawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stonefish_ros::Respawn >::value();
  }
  static const char* value(const ::stonefish_ros::RespawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stonefish_ros::RespawnResponse> should match
// service_traits::DataType< ::stonefish_ros::Respawn >
template<>
struct DataType< ::stonefish_ros::RespawnResponse>
{
  static const char* value()
  {
    return DataType< ::stonefish_ros::Respawn >::value();
  }
  static const char* value(const ::stonefish_ros::RespawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STONEFISH_ROS_MESSAGE_RESPAWN_H
