// Generated by gencpp from file stonefish_ros/SonarSettings.msg
// DO NOT EDIT!


#ifndef STONEFISH_ROS_MESSAGE_SONARSETTINGS_H
#define STONEFISH_ROS_MESSAGE_SONARSETTINGS_H

#include <ros/service_traits.h>


#include <stonefish_ros/SonarSettingsRequest.h>
#include <stonefish_ros/SonarSettingsResponse.h>


namespace stonefish_ros
{

struct SonarSettings
{

typedef SonarSettingsRequest Request;
typedef SonarSettingsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SonarSettings
} // namespace stonefish_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stonefish_ros::SonarSettings > {
  static const char* value()
  {
    return "3dd7b67bb9c281a0e1f972514667dae6";
  }

  static const char* value(const ::stonefish_ros::SonarSettings&) { return value(); }
};

template<>
struct DataType< ::stonefish_ros::SonarSettings > {
  static const char* value()
  {
    return "stonefish_ros/SonarSettings";
  }

  static const char* value(const ::stonefish_ros::SonarSettings&) { return value(); }
};


// service_traits::MD5Sum< ::stonefish_ros::SonarSettingsRequest> should match
// service_traits::MD5Sum< ::stonefish_ros::SonarSettings >
template<>
struct MD5Sum< ::stonefish_ros::SonarSettingsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stonefish_ros::SonarSettings >::value();
  }
  static const char* value(const ::stonefish_ros::SonarSettingsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stonefish_ros::SonarSettingsRequest> should match
// service_traits::DataType< ::stonefish_ros::SonarSettings >
template<>
struct DataType< ::stonefish_ros::SonarSettingsRequest>
{
  static const char* value()
  {
    return DataType< ::stonefish_ros::SonarSettings >::value();
  }
  static const char* value(const ::stonefish_ros::SonarSettingsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stonefish_ros::SonarSettingsResponse> should match
// service_traits::MD5Sum< ::stonefish_ros::SonarSettings >
template<>
struct MD5Sum< ::stonefish_ros::SonarSettingsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stonefish_ros::SonarSettings >::value();
  }
  static const char* value(const ::stonefish_ros::SonarSettingsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stonefish_ros::SonarSettingsResponse> should match
// service_traits::DataType< ::stonefish_ros::SonarSettings >
template<>
struct DataType< ::stonefish_ros::SonarSettingsResponse>
{
  static const char* value()
  {
    return DataType< ::stonefish_ros::SonarSettings >::value();
  }
  static const char* value(const ::stonefish_ros::SonarSettingsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STONEFISH_ROS_MESSAGE_SONARSETTINGS_H
