(cl:defpackage stonefish_ros-srv
  (:use )
  (:export
   "RESPAWN"
   "<RESPAWN-REQUEST>"
   "RESPAWN-REQUEST"
   "<RESPAWN-RESPONSE>"
   "RESPAWN-RESPONSE"
   "SONARSETTINGS"
   "<SONARSETTINGS-REQUEST>"
   "SONARSETTINGS-REQUEST"
   "<SONARSETTINGS-RESPONSE>"
   "SONARSETTINGS-RESPONSE"
   "SONARSETTINGS2"
   "<SONARSETTINGS2-REQUEST>"
   "SONARSETTINGS2-REQUEST"
   "<SONARSETTINGS2-RESPONSE>"
   "SONARSETTINGS2-RESPONSE"
  ))

